export type DealerCrmLocale = "uk" | "cs";

export function resolveDealerCrmLocale(value: string | null | undefined): DealerCrmLocale {
  return value === "cs" ? "cs" : "uk";
}

export const applicationStatusLabels = {
  uk: {
    NEW: "Нова",
    IN_REVIEW: "На розгляді",
    NEED_INFO: "Потрібна інформація",
    CONTACTED: "Контакт встановлено",
    APPROVED: "Схвалено",
    REJECTED: "Відхилено",
  },
  cs: {
    NEW: "Nová",
    IN_REVIEW: "V řešení",
    NEED_INFO: "Chybí informace",
    CONTACTED: "Kontaktováno",
    APPROVED: "Schváleno",
    REJECTED: "Zamítnuto",
  },
} as const;

export const financingStatusLabels = {
  uk: {
    NEW: "Нова",
    QUALIFYING: "Перевірка",
    DOCUMENTS_PENDING: "Очікуємо документи",
    SUBMITTED: "Подано",
    APPROVED: "Схвалено",
    REJECTED: "Відхилено",
    FUNDED: "Профінансовано",
  },
  cs: {
    NEW: "Nový",
    QUALIFYING: "Prověření",
    DOCUMENTS_PENDING: "Čekáme na dokumenty",
    SUBMITTED: "Podáno",
    APPROVED: "Schváleno",
    REJECTED: "Zamítnuto",
    FUNDED: "Profinancováno",
  },
} as const;

export const partnerStatusLabels = {
  uk: {
    NEW: "Нова",
    IN_REVIEW: "На розгляді",
    CONTACTED: "Контакт встановлено",
    APPROVED: "Схвалено",
    REJECTED: "Відхилено",
  },
  cs: {
    NEW: "Nová",
    IN_REVIEW: "V řešení",
    CONTACTED: "Kontaktováno",
    APPROVED: "Schváleno",
    REJECTED: "Zamítnuto",
  },
} as const;

export const availabilityLabels = {
  uk: {
    IN_TRANSIT: "В дорозі",
    ON_SITE: "На майданчику",
    SOLD: "Продано",
  },
  cs: {
    IN_TRANSIT: "Na cestě",
    ON_SITE: "Na ploše",
    SOLD: "Prodáno",
  },
} as const;

export const membershipRoleLabels = {
  uk: {
    DEALER_OWNER: "Власник дилера",
    DEALER_MANAGER: "Менеджер дилера",
    DEALER_SALES: "Продажі дилера",
  },
  cs: {
    DEALER_OWNER: "Majitel dealera",
    DEALER_MANAGER: "Manažer dealera",
    DEALER_SALES: "Prodej dealer",
  },
} as const;

export const topicLabels = {
  uk: {
    LEASING: "Лізинг",
    FUEL: "Паливна програма",
    VEHICLE: "Запит по авто",
    CAREER: "Кар'єра",
    OTHER: "Інше",
  },
  cs: {
    LEASING: "Leasing",
    FUEL: "Palivový program",
    VEHICLE: "Dotaz na vozidlo",
    CAREER: "Kariéra",
    OTHER: "Jiné",
  },
} as const;

export const adminCrmUk = {
  lang: "uk",
  metaTitle: "YASKRAVA • Центральна CRM",
  eyebrow: "YASKRAVA • CRM",
  title: "Центральна CRM",
  loggedInAs: "Вхід як",
  logout: "Вийти",
  menuFinancing: "Фінансування",
  menuVacancies: "Вакансії",
  menuVehicles: "Авто Yaskrava",
  menuDealers: "Дилери",
  dealerPipeline: "Підключення з сайту",
  dealerPipelineText: "Заявка з сайту, перевірка та підключення дилера тепер працюють як один безперервний процес.",
  incomingDealerLeads: "Нові заявки на підключення",
  incomingDealerLeadsText: "Після перевірки ви відразу створюєте дилера з цієї заявки без дублювання даних.",
  noIncomingDealerLeads: "Поки що немає нових заявок на підключення.",
  connectDealerFromLead: "Підключити дилера з цієї заявки",
  manualProvisionTitle: "Ручне підключення дилера",
  manualProvisionText: "Використовуйте тільки якщо дилера треба підключити без попередньої заявки з сайту.",
  activeDealers: "Підключені дилери",
  activeUsers: "Платформені користувачі",
  openFinancing: "Відкриті фінансування",
  newLeads: "Нові заявки",
  newPartnerLeads: "Нові партнерські заявки",
  provisionDealer: "Підключення дилера",
  provisionDealerText: "Створення дилера, піддомену та акаунта власника в один крок.",
  dealerCreated: "Дилера створено",
  dealerError: "Не вдалося підключити дилера. Перевірте унікальність slug та email і спробуйте ще раз.",
  dealerName: "Назва дилера",
  subdomainSlug: "Slug піддомену",
  legalName: "Юридична назва",
  supportEmail: "Email підтримки",
  supportPhone: "Телефон підтримки",
  ownerEmail: "Email власника",
  ownerFirstName: "Ім'я власника",
  ownerLastName: "Прізвище власника",
  ownerPassword: "Пароль власника",
  provisionButton: "Підключити дилера",
  dealerNetwork: "Мережа дилерів",
  noOwner: "Власника не призначено",
  noSupportEmail: "Email підтримки не вказано",
  uploadVehicle: "Додати авто",
  uploadVehicleText: "Додавайте тільки авто Yaskrava для головного сайту.",
  platformDealerLabel: "Головний сайт",
  dealer: "Дилер",
  selectDealer: "Оберіть дилера",
  titleField: "Назва",
  stockNumber: "Складський номер",
  priceCzk: "Ціна CZK",
  uploadPhoto: "Завантажити фото",
  uploadVideo: "Завантажити відео",
  description: "Опис",
  imageUrl: "Посилання на фото",
  videoUrl: "Посилання на відео",
  uploadVehicleButton: "Додати авто",
  noPlatformVehicles: "Поки що немає авто Yaskrava.",
  publishedLabel: "Опубліковано",
  hiddenLabel: "Приховано",
  featuredLabel: "Рекомендоване",
  priceOnRequest: "Ціна за запитом",
  noImage: "Немає фото",
  videoAttached: "Відео додано",
  noVideo: "Без відео",
  markSold: "Позначити як продано",
  availability: "Наявність",
  availabilityOnSite: "На майданчику",
  availabilityTransit: "В дорозі",
  availabilitySold: "Продано",
  dealerLeads: "Заявок",
  dealerApproved: "Схвалено",
  dealerRejected: "Відхилено",
  vacanciesHeading: "Вакансії (Career)",
  vacanciesText: "Керуйте вакансіями, які показуються на сторінці кар'єри головного сайту.",
  vacancyTitle: "Назва вакансії",
  vacancyCity: "Місто",
  vacancyType: "Тип зайнятості",
  sortOrder: "Порядок сортування",
  createVacancyButton: "Додати вакансію",
  archiveVacancy: "Архівувати вакансію",
  noVacancies: "Поки що немає вакансій.",
  partnerRequests: "Заявки на підключення",
  partnerRequestsText: "Заявки з сайту, які переходять у підключених дилерів без дублювання карток.",
  archived: "Архів",
  update: "Оновити",
  save: "Зберегти",
  saveNote: "Зберегти нотатку",
  partnerNotePlaceholder: "Нотатка по партнеру…",
  noPartnerRequests: "Поки що немає партнерських заявок.",
  client: "Клієнт",
  dealerColumn: "Дилер",
  leadStatus: "Статус заявки",
  financing: "Фінансування",
  actions: "Дії",
  delete: "Видалити",
  internalNotePlaceholder: "Внутрішня нотатка…",
  noApplications: "Поки що немає заявок.",
  calcAttached: "розрахунок додано",
  convertedDealer: "Підключений дилер",
  fleetLabel: "Автопарк",
} as const;

export const dealerCrmCopy = {
  uk: {
    titleMeta: "CRM дилера",
    eyebrow: "CRM дилера",
    title: "Міні CRM",
    logout: "Вийти",
    vehicles: "Авто",
    leads: "Заявки",
    openFinancing: "Відкриті фінансування",
    leadInbox: "Вхідні заявки",
    save: "Зберегти",
    saveNote: "Зберегти нотатку",
    dealerNotePlaceholder: "Нотатка дилера…",
    noLeads: "Поки що немає заявок.",
    addVehicle: "Додати авто",
    addVehicleText: "Опублікуйте нове авто на піддомені дилера та в потоці фінансування.",
    titlePlaceholder: "BMW 320d Touring • 2021 • Автомат",
    titleField: "Назва",
    stockNumber: "Складський номер",
    vinLast6: "VIN останні 6",
    make: "Марка",
    model: "Модель",
    year: "Рік",
    mileageKm: "Пробіг (км)",
    fuel: "Паливо",
    fuelPlaceholder: "Дизель",
    transmission: "Коробка",
    transmissionPlaceholder: "Автомат",
    priceCzk: "Ціна CZK",
    availability: "Наявність",
    uploadPhoto: "Завантажити фото",
    uploadVideo: "Завантажити відео",
    imageUrl: "Посилання на фото",
    videoUrl: "Посилання на відео",
    description: "Опис",
    descriptionPlaceholder: "Короткий опис авто та його сильних сторін.",
    leasingEligible: "Підходить для лізингу",
    addVehicleButton: "Додати авто",
    vehiclesHeading: "Автомобілі",
    noVehicles: "Поки що немає авто.",
    published: "Опубліковано",
    featured: "Рекомендоване",
    delete: "Видалити оголошення",
    loginTitle: "Вхід дилера",
    loginText: "Увійдіть, щоб керувати власними авто, заявками та статусами фінансування.",
    signIn: "Увійти",
    email: "Email",
    password: "Пароль",
    emailPlaceholder: "dealer@yaskrava.local",
    passwordPlaceholder: "Ваш пароль",
    errorRate: "Забагато спроб входу. Спробуйте трохи пізніше.",
    errorDealer: "Цей акаунт не прив'язаний до поточного дилера.",
    errorCredentials: "Невірний email або пароль.",
    language: "Мова CRM",
    leadVehicle: "Авто",
    priceOnRequest: "Ціна за запитом",
    platformAccess: "доступ платформи",
  },
  cs: {
    titleMeta: "Dealer CRM",
    eyebrow: "Dealer CRM",
    title: "Mini CRM",
    logout: "Odhlásit se",
    vehicles: "Vozidla",
    leads: "Leady",
    openFinancing: "Otevřená financování",
    leadInbox: "Příchozí leady",
    save: "Uložit",
    saveNote: "Uložit poznámku",
    dealerNotePlaceholder: "Poznámka dealera…",
    noLeads: "Zatím žádné leady.",
    addVehicle: "Přidat vozidlo",
    addVehicleText: "Publikujte nové auto na dealer subdoméně a ve flow financování.",
    titlePlaceholder: "BMW 320d Touring • 2021 • Automat",
    titleField: "Název",
    stockNumber: "Skladové číslo",
    vinLast6: "VIN posledních 6",
    make: "Značka",
    model: "Model",
    year: "Rok",
    mileageKm: "Nájezd (km)",
    fuel: "Palivo",
    fuelPlaceholder: "Diesel",
    transmission: "Převodovka",
    transmissionPlaceholder: "Automat",
    priceCzk: "Cena CZK",
    availability: "Dostupnost",
    uploadPhoto: "Nahrát foto",
    uploadVideo: "Nahrát video",
    imageUrl: "URL obrázku",
    videoUrl: "URL videa",
    description: "Popis",
    descriptionPlaceholder: "Krátký popis vozidla a jeho hlavních výhod.",
    leasingEligible: "Vhodné pro leasing",
    addVehicleButton: "Přidat vozidlo",
    vehiclesHeading: "Vozidla",
    noVehicles: "Zatím žádná vozidla.",
    published: "Publikováno",
    featured: "Doporučené",
    delete: "Smazat inzerát",
    loginTitle: "Přihlášení dealera",
    loginText: "Přihlaste se pro správu vlastních aut, leadů a stavů financování.",
    signIn: "Přihlásit se",
    email: "E-mail",
    password: "Heslo",
    emailPlaceholder: "dealer@yaskrava.local",
    passwordPlaceholder: "Vaše heslo",
    errorRate: "Příliš mnoho pokusů o přihlášení. Zkuste to později.",
    errorDealer: "Tento účet není přiřazen k aktuálnímu dealerovi.",
    errorCredentials: "Neplatný e-mail nebo heslo.",
    language: "Jazyk CRM",
    leadVehicle: "Vozidlo",
    priceOnRequest: "Cena na vyžádání",
    platformAccess: "platformní přístup",
  },
} as const;
