-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'DEALER_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'DEALER_REACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'DEALER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'DEALER_PASSWORD_RESET';
