-- CreateEnum
CREATE TYPE "CzechRegion" AS ENUM ('Praha', 'STREDOCESKY', 'JIHOCESKY', 'PLZENSKY', 'KARLOVARSKY', 'USTECKY', 'LIBERECKY', 'KRALOVEHRADECKY', 'PARDUBICKY', 'VYSOCINA', 'JIHOMORAVSKY', 'OLOMOUCKY', 'ZLINSKY', 'MORAVSKOSLEZSKY');

-- AlterTable
ALTER TABLE "Dealer" ADD COLUMN "region" "CzechRegion";
ALTER TABLE "Dealer" ADD COLUMN "homeDelivery" BOOLEAN NOT NULL DEFAULT false;
